version: '3.4'

services:
  frontend:  
    image: graphclient
    build:
      context: ClientApp/
      dockerfile: Dockerfile
    ports:
      - 3000:80
  
  backend:
    image: graphexp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 7081:80

  proxy:
    image: nginx:1.22-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

